### ISSUE TITLE
PHP Fatal during ./kanboard worker

### ISSUE THREAD

**Issue by mauriziodidomenico** [kanboard/plugin-beanstalk#1]
`[fonzi@kanboard kanboard]$ ./kanboard worker

PHP Notice:  Undefined index: task in /home/fonzi/git/kanboard/app/Model/UserNotificationModel.php on line 25
PHP Notice:  Undefined index: task in /home/fonzi/git/kanboard/app/Job/NotificationJob.php on line 40
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Kanboard\Notification\WebhookNotification::notifyProject() must be of the type array, null given, called in /home/fonzi/git/kanboard/app/Model/ProjectNotificationModel.php on line 33 and defined in /home/fonzi/git/kanboard/app/Notification/WebhookNotification.php:36
Stack trace:
#0 /home/fonzi/git/kanboard/app/Model/ProjectNotificationModel.php(33): Kanboard\Notification\WebhookNotification->notifyProject(NULL, 'task.move.colum...', Array)
#1 /home/fonzi/git/kanboard/app/Job/NotificationJob.php(40): Kanboard\Model\ProjectNotificationModel->sendNotifications(NULL, 'task.move.colum...', Array)
#2 [internal function]: Kanboard\Job\NotificationJob->execute(Array, 'task.move.colum...', 'Kanboard\Event\...')
#3 /home/fonzi/git/kanboard/app/Core/Queue/JobHandler.php(55): call_user_func_array(Array, Array)
#4 /home/fonzi/git/kanboard/app/Core/Queue/QueueManager.php(71): Kanboard\Core\Queue\JobHandler->executeJob(Object(SimpleQueue\Job))
#5 /home/fonzi/git/kanboard/app/Consol in /home/fonzi/git/kanboard/app/Notification/WebhookNotification.php on line 36`

**Comment by fguillot** [comment]
What version of Kanboard are you using?

**Comment by mauriziodidomenico** [comment]
Application version: master
PHP version: 7.0.7
PHP SAPI: apache2handler
OS version: Linux 4.4.11-1-ARCH
Database driver: sqlite
Database version: 3.13.0
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
